# Default CPMA parameters from Olfert lab

name: olfert
r1: 0.06          # inner electrode radius [m]
r2: 0.061         # outer electrode radius [m]
L: 0.2            # length of chamber [m]
p: 1              # pressure [atm]
T: 293            # system temperature [K]
Q: 5e-5 # 3/1000/60      # volume flow rate [m^3/s]
omega_hat: 0.9697 # 32/33  # ratio of angular speeds