# Parameters from Olfert and Collings
# Nearly identical to the Ehara et al. case

name: olfert-collings
r2: 0.103                 # outer electrode radius [m]
r1: 0.1                   # inner electrode radius [m]
L: 0.2
omega_hat: 0.945
Q: 0.5/1000/60            # aerosol flowrate [m^3/s]
T: 295                    # system temperature [K]
p: 1                      # system pressure [atm]
m0: 900 * pi / 6 * 1e-27  # copy mass-mobility relation info (only used to find Rm)
Dm: 3